### ISSUE TITLE
Add Nuxt Loader

### ISSUE THREAD

**Issue by blowsie** [sanity-io/sanity-template-nuxt-clean#16]
**Is your feature request related to a problem? Please describe.**
The Nuxt Loader readme is a little lacking, and in its current state, even has syntax errors.

**Describe the solution you'd like**
It would be nice to see nuxt loader working in this example

**Describe alternatives you've considered**
Well, I tried to implement nuxt-loader in my own project but ran into issues.

**Additional context**
https://github.com/sanity-io/visual-editing/blob/main/packages/nuxt-loader/README.md

**Comment by tomaszter** [comment]
Same here. Would be very nice to see the nuxt loader integrated in this template. Thanks guys!

**Comment by rdunk** [comment]
The template has now been updated to include visual editing via the `@nuxtjs/sanity` module, which `@sanity/nuxt-loader` was deprecated in favour of. Hope this helps!
