### ISSUE TITLE
Images in post body not appearing

### ISSUE THREAD

**Issue by nickmesiano** [sanity-io/sanity-template-nuxt-clean#17]
**Is your feature request related to a problem? Please describe.**

Hello, when using the blog schema of this template, images embedded into post body do not appear. 
An image tag is rendered but there is no source. 

<img width="285" alt="Screenshot 2024-02-22 at 9 13 59 PM" src="https://github.com/sanity-io/sanity-template-nuxt-clean/assets/83598195/0ac60b64-dd52-4fb1-bb69-4299ebbc0ee3">

Project template : Blog (schema)

1. In CMS, Go to post creation page
2. In CMS, Embed image into post's body 
3. On App, The image tag will appear, but with no source url.

**Comment by nickmesiano** [comment]
Update: Installing portabletext and some other things as seen constructs the portable text image url for images in post body. 

This is not tidy (Re: Client Data) but has images in post body :

"BlockContent.vue"

`<script setup>

import { PortableText } from '@portabletext/vue';
import urlBuilder from '@sanity/image-url';
import { getImageDimensions } from '@sanity/asset-utils';
import { createClient } from "@sanity/client";
// import { projectId, dataset } from '../configfile'
//I should be importing this as a config file

// Barebones lazy-loaded image component

const SampleImageComponent = ({ value }) => {
  const client = createClient({ projectId : 'YOURID', dataset: 'YOURDATASET', apiVersion: 'YOURAPIVERSION', useCdn: false })
  const { width, height } = getImageDimensions(value);
  return h('img', {
    src: urlBuilder(client).image(value).width(800).fit('max').auto('format').url(),
    alt: value.alt || ' ',
    loading: 'lazy',
    style: {
      // Avoid jumping around with aspect-ratio CSS property
      aspectRatio: width / height,
    },
  });
};

const props =
  defineProps({
    blocks: {
      type: Array,
      required: true
    }
  });
</script>

<template>
  <PortableText
    :value="blocks"
    :components="{
      types: {
        image: SampleImageComponent,
      },
    }"
    />
</template>`

**Comment by rdunk** [comment]
Closing as this is expected behaviour.
