### ISSUE TITLE
useSanityVisualEditingState is not defined

### ISSUE THREAD

**Issue by HZooly** [sanity-io/sanity-template-nuxt-clean#20]
**Describe the bug**

500 error on demo page.

**To Reproduce**

1. Go to https://sanity-template-nuxt-clean.sanity.build/

**Screenshots**
<img width="713" alt="image" src="https://github.com/sanity-io/sanity-template-nuxt-clean/assets/7328625/e5ea663a-6643-438a-90c8-8142650409a6">

**Comment by rdunk** [comment]
Thanks for reporting! Deployment should now be fixed.
